"""Feature matching script using OpenCV BFMatcher.

It expects an NPZ database generated by :mod:`feature_extraction` and a
query image. The script recomputes features on the query image using the
same detector type and reports matches for each database image.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import cv2
import numpy as np

from feature_extraction import create_detector, deserialize_keypoints


def load_database(npz_path: Path):
    data = np.load(npz_path, allow_pickle=True)
    detector_name: str = str(data["detector"])
    images: List[str] = data["images"].tolist()
    keypoints_serialized = data["keypoints"].tolist()
    descriptors: List[np.ndarray] = data["descriptors"].tolist()
    keypoints = [deserialize_keypoints(kps) for kps in keypoints_serialized]
    return detector_name, images, keypoints, descriptors


def configure_matcher(detector: str) -> cv2.DescriptorMatcher:
    if detector.lower() == "orb":
        return cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)
    return cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)


def match_descriptors(
    matcher: cv2.DescriptorMatcher,
    query_desc: np.ndarray,
    train_desc: np.ndarray,
    ratio: float,
) -> List[cv2.DMatch]:
    if len(query_desc) == 0 or len(train_desc) == 0:
        return []
    knn_matches = matcher.knnMatch(query_desc, train_desc, k=2)
    good: List[cv2.DMatch] = []
    for m, n in knn_matches:
        if m.distance < ratio * n.distance:
            good.append(m)
    return good


def visualize_best(
    query_image: np.ndarray,
    query_kp: List[cv2.KeyPoint],
    train_image: np.ndarray,
    train_kp: List[cv2.KeyPoint],
    matches: List[cv2.DMatch],
    output_path: Path,
) -> None:
    result = cv2.drawMatches(query_image, query_kp, train_image, train_kp, matches, None)
    cv2.imwrite(str(output_path), result)
    print(f"Saved visualization to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Match query features against a precomputed database.")
    parser.add_argument("query_image", type=Path, help="Path to the query image.")
    parser.add_argument("database", type=Path, help="NPZ database produced by feature_extraction.py")
    parser.add_argument("--ratio", type=float, default=0.75, help="Lowe ratio test threshold.")
    parser.add_argument("--visualize", type=Path, default=None, help="Optional output image path for the best-matching training image.")
    args = parser.parse_args()

    detector_name, image_paths, db_keypoints, db_desc = load_database(args.database)
    detector = create_detector(detector_name, nfeatures=2000)
    matcher = configure_matcher(detector_name)

    query_img = cv2.imread(str(args.query_image), cv2.IMREAD_GRAYSCALE)
    if query_img is None:
        raise FileNotFoundError(f"Could not read query image '{args.query_image}'.")
    query_kp, query_desc = detector.detectAndCompute(query_img, None)
    if query_desc is None:
        query_desc = np.zeros((0, detector.descriptorSize()), dtype=db_desc[0].dtype if db_desc else np.uint8)

    image_scores: List[Tuple[int, int]] = []  # (count, index)
    best_visualization = None

    for idx, (train_path, train_kp, train_desc) in enumerate(zip(image_paths, db_keypoints, db_desc)):
        matches = match_descriptors(matcher, query_desc, train_desc, ratio=args.ratio)
        image_scores.append((len(matches), idx))
        print(f"{train_path}: {len(matches)} matches")

    image_scores.sort(reverse=True)
    if image_scores and image_scores[0][0] > 0:
        top_count, top_idx = image_scores[0]
        print(f"Best match: {image_paths[top_idx]} with {top_count} matches")
        if args.visualize:
            train_img = cv2.imread(str(image_paths[top_idx]), cv2.IMREAD_GRAYSCALE)
            matches = match_descriptors(matcher, query_desc, db_desc[top_idx], ratio=args.ratio)
            visualize_best(query_img, query_kp, train_img, db_keypoints[top_idx], matches, args.visualize)
    else:
        print("No matches found across the database.")


if __name__ == "__main__":
    main()
